version: '2.1'

services:
  db:
    image: registry.redhat.io/rhel8/postgresql-10
    hostname: psql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USER: openapi
      POSTGRESQL_PASSWORD: openapi
      POSTGRESQL_DATABASE: openapi_generator
